print('Please enter the following information so I can sell it for a profit!')
name1=input('First name : ')
name2=input('Last name : ')
grade=int(input('Grade (9-12):'))
studentId=input('student Id')
Login=input('Login :')
GPA=input('GPA (0.0-4.0):')

print("Your Information : ")
print("Login:",Login)
print('ID:',studentId)
print("name:",name1 + name2)
print('GPA:',GPA)
print('Grade:',grade)